import { requirePlatformOperator } from '@/lib/platform/auth';
import { listNotifications } from '@/lib/platform/ops-reads';
import { AdminActionForm } from '@/components/admin/action-form';
import { acknowledgeNotification } from '@/lib/platform/ops-actions';

export const dynamic = 'force-dynamic';

export default async function AdminNotificationsPage() {
  await requirePlatformOperator();
  const items = await listNotifications({ includeAcknowledged: false, limit: 100 });
  return (
    <div className="admin-card">
      <h2>Admin notifications {items.length > 0 ? <span className="admin-tag warn">{items.length} open</span> : <span className="admin-tag ok">all clear</span>}</h2>
      <p className="admin-note">High-value platform events (failed-payment spikes, active kill switches, stuck syncs, security incidents). Deduped by key while unacknowledged (no flood). Generated by scripts/platform-admin-notify.mjs (scheduled) — see docs.</p>
      {items.length === 0 ? <p className="admin-note">No open notifications.</p> : (
        <table className="admin-table"><thead><tr><th>When</th><th>Severity</th><th>Kind</th><th>Title</th><th>Detail</th><th></th></tr></thead>
          <tbody>{items.map((n) => (
            <tr key={n.id}><td className="admin-note">{new Date(n.createdAt).toISOString().slice(0, 16).replace('T', ' ')}</td>
              <td><span className={`admin-tag ${n.severity === 'critical' ? 'bad' : n.severity === 'warning' ? 'warn' : ''}`}>{n.severity}</span></td>
              <td>{n.kind}</td><td>{n.title}</td><td className="admin-note">{n.detail ?? '—'}</td>
              <td><AdminActionForm action={acknowledgeNotification} submitLabel="Ack" hidden={{ id: n.id }} /></td></tr>
          ))}</tbody></table>
      )}
    </div>
  );
}
